# Generated by Django 4.2.7 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazoneDataScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=100)),
                ('product_price', models.TextField(max_length=100)),
                ('product_time', models.TextField(max_length=100)),
                ('product_image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
